import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  FileBarChart, Download, Share2, AlertTriangle, Shield, 
  FileCheck, ClipboardCheck, Users, TrendingUp, TrendingDown,
  Activity, Target, Zap, Brain, Loader2, Sparkles, Eye, BarChart3
} from "lucide-react";
import { 
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, 
  AreaChart, Area, RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  ComposedChart, ScatterChart, Scatter,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer 
} from "recharts";
import { base44 } from "@/api/base44Client";
import QuickActionPanel from "./QuickActionPanel";

const COLORS = {
  critical: '#ef4444',
  high: '#f97316',
  medium: '#eab308',
  low: '#3b82f6'
};

export default function ReportingDashboard({ data }) {
  const { risks, compliance, controls, audits, incidents, vendors } = data;
  const [visualMode, setVisualMode] = useState("overview");
  const [aiInsights, setAiInsights] = useState(null);
  const [generatingInsights, setGeneratingInsights] = useState(false);
  const [quickActionOpen, setQuickActionOpen] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [selectedIssue, setSelectedIssue] = useState(null);
  const [selectedIssueType, setSelectedIssueType] = useState(null);

  // Calculate metrics
  const criticalRisks = risks.filter(r => r.risk_level === 'critical').length;
  const highRisks = risks.filter(r => r.risk_level === 'high').length;
  const compliantItems = compliance.filter(c => c.status === 'compliant').length;
  const complianceRate = compliance.length ? Math.round((compliantItems / compliance.length) * 100) : 0;
  const effectiveControls = controls.filter(c => c.status === 'effective').length;
  const controlEffectiveness = controls.length ? Math.round((effectiveControls / controls.length) * 100) : 0;
  const openIncidents = incidents.filter(i => i.status !== 'closed').length;
  const criticalVendors = vendors.filter(v => v.criticality === 'critical').length;

  // Risk distribution
  const riskDistribution = [
    { name: 'Critical', value: risks.filter(r => r.risk_level === 'critical').length, color: COLORS.critical },
    { name: 'High', value: risks.filter(r => r.risk_level === 'high').length, color: COLORS.high },
    { name: 'Medium', value: risks.filter(r => r.risk_level === 'medium').length, color: COLORS.medium },
    { name: 'Low', value: risks.filter(r => r.risk_level === 'low').length, color: COLORS.low }
  ];

  // Compliance trend
  const complianceTrend = [
    { month: 'Jan', rate: 72 },
    { month: 'Feb', rate: 75 },
    { month: 'Mar', rate: 78 },
    { month: 'Apr', rate: 82 },
    { month: 'May', rate: 85 },
    { month: 'Jun', rate: complianceRate }
  ];

  // Control effectiveness by category
  const controlsByCategory = controls.reduce((acc, c) => {
    const cat = c.control_type || 'Other';
    if (!acc[cat]) acc[cat] = { total: 0, effective: 0 };
    acc[cat].total++;
    if (c.status === 'effective') acc[cat].effective++;
    return acc;
  }, {});

  const controlData = Object.keys(controlsByCategory).map(cat => ({
    category: cat,
    effectiveness: Math.round((controlsByCategory[cat].effective / controlsByCategory[cat].total) * 100),
    total: controlsByCategory[cat].total,
    effective: controlsByCategory[cat].effective
  }));

  // Domain breakdown for controls
  const controlsByDomain = controls.reduce((acc, c) => {
    const domain = c.domain || 'Other';
    if (!acc[domain]) acc[domain] = { total: 0, effective: 0, ineffective: 0 };
    acc[domain].total++;
    if (c.status === 'effective') acc[domain].effective++;
    if (c.status === 'ineffective') acc[domain].ineffective++;
    return acc;
  }, {});

  const domainData = Object.keys(controlsByDomain).map(domain => ({
    domain: domain.replace(/_/g, ' '),
    effectiveness: Math.round((controlsByDomain[domain].effective / controlsByDomain[domain].total) * 100) || 0,
    effective: controlsByDomain[domain].effective,
    ineffective: controlsByDomain[domain].ineffective,
    total: controlsByDomain[domain].total
  }));

  // Audit findings severity
  const auditsByStatus = audits.reduce((acc, a) => {
    acc[a.status] = (acc[a.status] || 0) + 1;
    return acc;
  }, {});

  const auditStatusData = Object.keys(auditsByStatus).map(status => ({
    status: status.replace(/_/g, ' '),
    count: auditsByStatus[status]
  }));

  // Incident trends
  const incidentTrendData = [
    { month: "Jan", security: 5, compliance: 3, operational: 7 },
    { month: "Feb", security: 4, compliance: 4, operational: 6 },
    { month: "Mar", security: 3, compliance: 2, operational: 5 },
    { month: "Apr", security: 4, compliance: 3, operational: 6 },
    { month: "May", security: 2, compliance: 2, operational: 4 },
    { month: "Jun", security: 3, compliance: 1, operational: 3 }
  ];

  // Framework compliance
  const frameworks = [...new Set(compliance.map(c => c.framework))].filter(Boolean);
  const frameworkComplianceData = frameworks.map(fw => {
    const items = compliance.filter(c => c.framework === fw);
    const compliant = items.filter(c => c.status === 'verified' || c.status === 'implemented').length;
    return {
      framework: fw,
      compliance: items.length > 0 ? Math.round((compliant / items.length) * 100) : 0,
      total: items.length,
      compliant
    };
  });

  // Auto-generate insights on mount
  useEffect(() => {
    if (!hasAutoGenerated && risks.length > 0) {
      setHasAutoGenerated(true);
      const timer = setTimeout(() => generateAIInsights(), 800);
      return () => clearTimeout(timer);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [risks.length]);

  const generateAIInsights = async () => {
    setGeneratingInsights(true);
    try {
      const prompt = `Analyze this GRC data and provide strategic executive insights:

DATA OVERVIEW:
- Total Risks: ${risks.length} (${criticalRisks} critical, ${highRisks} high)
- Compliance Rate: ${complianceRate}% (${compliantItems}/${compliance.length})
- Control Effectiveness: ${controlEffectiveness}% (${effectiveControls}/${controls.length})
- Open Incidents: ${openIncidents}
- Active Audits: ${audits.filter(a => a.status === 'in_progress').length}
- Critical Vendors: ${criticalVendors}

FRAMEWORK COVERAGE:
${frameworkComplianceData.map(f => `${f.framework}: ${f.compliance}% (${f.compliant}/${f.total})`).join('\n')}

Provide a 3-4 sentence executive insight covering:
1. Overall GRC posture assessment (strong/moderate/needs improvement)
2. Top priority areas requiring immediate attention
3. Key strengths to leverage
4. Strategic recommendations for leadership

Be direct, actionable, and data-driven.`;

      const insights = await base44.integrations.Core.InvokeLLM({ prompt });
      setAiInsights(insights);
    } catch (error) {
      console.error(error);
      setAiInsights("Unable to generate insights at this time.");
    } finally {
      setGeneratingInsights(false);
    }
  };

  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      return (
        <div className="bg-[#0f1623] border border-[#2a3548] rounded-lg px-3 py-2 shadow-xl">
          <p className="text-xs text-white font-medium mb-1">{payload[0].payload.framework || payload[0].payload.category || payload[0].payload.domain || payload[0].name}</p>
          {payload.map((entry, idx) => (
            <p key={idx} className="text-xs" style={{ color: entry.color }}>
              {entry.name}: {entry.value}
            </p>
          ))}
        </div>
      );
    }
    return null;
  };

  const openQuickAction = (issue, type) => {
    setSelectedIssue(issue);
    setSelectedIssueType(type);
    setQuickActionOpen(true);
  };

  // Get critical issues for quick action
  const criticalIssues = [
    ...risks.filter(r => r.risk_level === 'critical' || r.impact >= 4).slice(0, 3).map(r => ({...r, type: 'risk'})),
    ...compliance.filter(c => c.status === 'non_compliant' || c.status === 'not_started').slice(0, 3).map(c => ({...c, type: 'compliance'}))
  ];

  const quickReports = [
    { 
      title: 'Executive Summary', 
      description: 'High-level overview for leadership',
      icon: Target,
      color: 'from-indigo-500 to-purple-500'
    },
    { 
      title: 'Risk Register', 
      description: 'Complete risk inventory and analysis',
      icon: AlertTriangle,
      color: 'from-rose-500 to-orange-500'
    },
    { 
      title: 'Compliance Status', 
      description: 'Framework compliance and gaps',
      icon: FileCheck,
      color: 'from-emerald-500 to-teal-500'
    },
    { 
      title: 'Control Effectiveness', 
      description: 'Control testing and performance',
      icon: Shield,
      color: 'from-blue-500 to-cyan-500'
    },
    { 
      title: 'Audit Summary', 
      description: 'Findings and remediation status',
      icon: ClipboardCheck,
      color: 'from-purple-500 to-pink-500'
    },
    { 
      title: 'Vendor Risk Report', 
      description: 'Third-party risk assessment',
      icon: Users,
      color: 'from-amber-500 to-yellow-500'
    }
  ];

  return (
    <div className="space-y-6">
      {/* AI Insights */}
      <Card className="bg-gradient-to-br from-[#1a2332] to-[#151d2e] border-[#2a3548] shadow-xl">
        <CardHeader className="border-b border-[#2a3548]">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-3 rounded-xl bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-indigo-500/30">
                <Brain className="h-6 w-6 text-indigo-400" />
              </div>
              <div>
                <CardTitle className="text-xl font-bold text-white">AI Strategic Insights</CardTitle>
                <p className="text-slate-400 text-sm mt-1">Executive-level analysis and recommendations</p>
              </div>
            </div>
            {!aiInsights && (
              <Button
                onClick={generateAIInsights}
                disabled={generatingInsights}
                className="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700"
              >
                {generatingInsights ? (
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                ) : (
                  <Sparkles className="h-4 w-4 mr-2" />
                )}
                {generatingInsights ? 'Analyzing...' : 'Generate Insights'}
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent className="pt-4">
          {aiInsights ? (
            <p className="text-slate-200 leading-relaxed">{aiInsights}</p>
          ) : (
            <p className="text-slate-500 italic text-sm">Click "Generate Insights" to get AI-powered strategic analysis of your GRC data</p>
          )}
        </CardContent>
      </Card>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <Card className="bg-gradient-to-br from-rose-500/10 to-orange-500/10 border-rose-500/20">
          <CardContent className="p-3 sm:p-6">
            <div className="flex items-center justify-between mb-2 sm:mb-4">
              <div className="p-2 sm:p-3 rounded-xl bg-rose-500/10">
                <AlertTriangle className="h-4 w-4 sm:h-6 sm:w-6 text-rose-400" />
              </div>
              <Badge className="bg-rose-500/10 text-rose-400 text-[10px] sm:text-xs">
                {criticalRisks + highRisks} High+
              </Badge>
            </div>
            <h3 className="text-[10px] sm:text-sm font-medium text-slate-400 mb-1">Total Risks</h3>
            <p className="text-xl sm:text-3xl font-bold text-white">{risks.length}</p>
            <div className="flex items-center gap-1 mt-1 sm:mt-2 text-[10px] sm:text-xs text-rose-400">
              <TrendingUp className="h-2.5 w-2.5 sm:h-3 sm:w-3" />
              <span className="hidden sm:inline">3% from last month</span>
              <span className="sm:hidden">+3%</span>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-emerald-500/10 to-teal-500/10 border-emerald-500/20">
          <CardContent className="p-3 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="p-3 rounded-xl bg-emerald-500/10">
                <FileCheck className="h-6 w-6 text-emerald-400" />
              </div>
              <Badge className="bg-emerald-500/10 text-emerald-400">
                {complianceRate}%
              </Badge>
            </div>
            <h3 className="text-sm font-medium text-slate-400 mb-1">Compliance Rate</h3>
            <p className="text-3xl font-bold text-white">{compliantItems}/{compliance.length}</p>
            <div className="flex items-center gap-1 mt-2 text-xs text-emerald-400">
              <TrendingUp className="h-3 w-3" />
              <span>5% improvement</span>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-blue-500/10 to-cyan-500/10 border-blue-500/20">
          <CardContent className="p-3 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="p-3 rounded-xl bg-blue-500/10">
                <Shield className="h-6 w-6 text-blue-400" />
              </div>
              <Badge className="bg-blue-500/10 text-blue-400">
                {controlEffectiveness}%
              </Badge>
            </div>
            <h3 className="text-sm font-medium text-slate-400 mb-1">Controls</h3>
            <p className="text-3xl font-bold text-white">{effectiveControls}/{controls.length}</p>
            <div className="flex items-center gap-1 mt-2 text-xs text-blue-400">
              <Activity className="h-3 w-3" />
              <span>Effective controls</span>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-purple-500/10 to-pink-500/10 border-purple-500/20">
          <CardContent className="p-3 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="p-3 rounded-xl bg-purple-500/10">
                <ClipboardCheck className="h-6 w-6 text-purple-400" />
              </div>
              <Badge className="bg-purple-500/10 text-purple-400">
                {audits.length} Total
              </Badge>
            </div>
            <h3 className="text-sm font-medium text-slate-400 mb-1">Open Incidents</h3>
            <p className="text-3xl font-bold text-white">{openIncidents}</p>
            <div className="flex items-center gap-1 mt-2 text-xs text-purple-400">
              <TrendingDown className="h-3 w-3" />
              <span>Down from last week</span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Interactive Data Visualizations */}
      <Card className="bg-[#1a2332] border-[#2a3548]">
        <CardHeader className="border-b border-[#2a3548]">
          <div className="flex items-center justify-between">
            <CardTitle className="text-white flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-cyan-400" />
              Interactive Analytics
            </CardTitle>
            <div className="flex items-center gap-1 bg-[#0f1623] border border-[#2a3548] rounded-lg p-0.5 overflow-x-auto scrollbar-thin">
              <Button
                size="sm"
                variant={visualMode === "overview" ? "default" : "ghost"}
                onClick={() => setVisualMode("overview")}
                className="h-7 px-3 text-xs flex-shrink-0"
              >
                Overview
              </Button>
              <Button
                size="sm"
                variant={visualMode === "risks" ? "default" : "ghost"}
                onClick={() => setVisualMode("risks")}
                className="h-7 px-3 text-xs flex-shrink-0"
              >
                Risks
              </Button>
              <Button
                size="sm"
                variant={visualMode === "compliance" ? "default" : "ghost"}
                onClick={() => setVisualMode("compliance")}
                className="h-7 px-3 text-xs flex-shrink-0"
              >
                Compliance
              </Button>
              <Button
                size="sm"
                variant={visualMode === "controls" ? "default" : "ghost"}
                onClick={() => setVisualMode("controls")}
                className="h-7 px-3 text-xs flex-shrink-0"
              >
                Controls
              </Button>
              <Button
                size="sm"
                variant={visualMode === "incidents" ? "default" : "ghost"}
                onClick={() => setVisualMode("incidents")}
                className="h-7 px-3 text-xs flex-shrink-0"
              >
                Incidents
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="pt-6">
          {visualMode === "overview" && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4 text-rose-400" />
                  Risk Distribution
                </h3>
                <ResponsiveContainer width="100%" height="85%">
                  <PieChart>
                    <Pie
                      data={riskDistribution}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={90}
                      paddingAngle={5}
                      dataKey="value"
                      label={(entry) => `${entry.name}: ${entry.value}`}
                      labelLine={{ stroke: '#64748b', strokeWidth: 1 }}
                    >
                      {riskDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip content={<CustomTooltip />} />
                  </PieChart>
                </ResponsiveContainer>
              </div>

              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
                  <TrendingUp className="h-4 w-4 text-emerald-400" />
                  Compliance Progress
                </h3>
                <ResponsiveContainer width="100%" height="85%">
                  <AreaChart data={complianceTrend}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis dataKey="month" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                    <YAxis domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                    <Tooltip content={<CustomTooltip />} />
                    <Area type="monotone" dataKey="rate" stroke="#10b981" fill="#10b981" fillOpacity={0.6} strokeWidth={2} />
                  </AreaChart>
                </ResponsiveContainer>
              </div>

              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6 lg:col-span-2">
                <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
                  <Shield className="h-4 w-4 text-blue-400" />
                  Control Effectiveness by Domain
                </h3>
                <ResponsiveContainer width="100%" height="85%">
                  <BarChart data={domainData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis dataKey="domain" tick={{ fill: '#94a3b8', fontSize: 10 }} angle={-25} textAnchor="end" height={80} />
                    <YAxis tick={{ fill: '#94a3b8' }} domain={[0, 100]} />
                    <Tooltip content={<CustomTooltip />} />
                    <Legend />
                    <Bar dataKey="effectiveness" fill="#3b82f6" name="Effectiveness %" radius={[8, 8, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {visualMode === "risks" && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Risk Severity Breakdown</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <PieChart>
                    <Pie
                      data={riskDistribution}
                      cx="50%"
                      cy="50%"
                      innerRadius={50}
                      outerRadius={90}
                      paddingAngle={4}
                      dataKey="value"
                    >
                      {riskDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip content={<CustomTooltip />} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Risk Category Distribution</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <BarChart data={riskDistribution}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis dataKey="name" tick={{ fill: '#94a3b8' }} />
                    <YAxis tick={{ fill: '#94a3b8' }} />
                    <Tooltip content={<CustomTooltip />} />
                    <Bar dataKey="value" fill="#ef4444" radius={[8, 8, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {visualMode === "compliance" && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Framework Compliance Rates</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <BarChart data={frameworkComplianceData} layout="vertical">
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis type="number" domain={[0, 100]} tick={{ fill: '#94a3b8' }} />
                    <YAxis dataKey="framework" type="category" tick={{ fill: '#94a3b8' }} width={100} />
                    <Tooltip content={<CustomTooltip />} />
                    <Bar dataKey="compliance" fill="#10b981" radius={[0, 8, 8, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Compliance Trend (6 Months)</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <LineChart data={complianceTrend}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis dataKey="month" tick={{ fill: '#94a3b8' }} />
                    <YAxis domain={[0, 100]} tick={{ fill: '#94a3b8' }} />
                    <Tooltip content={<CustomTooltip />} />
                    <Line type="monotone" dataKey="rate" stroke="#10b981" strokeWidth={3} dot={{ fill: '#10b981', r: 5 }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {visualMode === "controls" && (
            <div className="grid grid-cols-1 gap-6">
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Control Effectiveness by Domain</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <BarChart data={domainData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis dataKey="domain" tick={{ fill: '#94a3b8', fontSize: 10 }} angle={-25} textAnchor="end" height={80} />
                    <YAxis tick={{ fill: '#94a3b8' }} domain={[0, 100]} />
                    <Tooltip content={<CustomTooltip />} />
                    <Legend />
                    <Bar dataKey="effectiveness" fill="#3b82f6" name="Effectiveness %" radius={[8, 8, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Control Type Performance</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <RadarChart data={controlData.slice(0, 6)}>
                    <PolarGrid stroke="#2a3548" />
                    <PolarAngleAxis dataKey="category" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                    <PolarRadiusAxis angle={90} domain={[0, 100]} tick={{ fill: '#94a3b8' }} />
                    <Radar name="Effectiveness" dataKey="effectiveness" stroke="#3b82f6" fill="#3b82f6" fillOpacity={0.6} strokeWidth={2} />
                    <Tooltip content={<CustomTooltip />} />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {visualMode === "incidents" && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Incident Trends by Type</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <AreaChart data={incidentTrendData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis dataKey="month" tick={{ fill: '#94a3b8' }} />
                    <YAxis tick={{ fill: '#94a3b8' }} />
                    <Tooltip content={<CustomTooltip />} />
                    <Legend />
                    <Area type="monotone" dataKey="security" stackId="1" stroke="#ef4444" fill="#ef4444" fillOpacity={0.6} />
                    <Area type="monotone" dataKey="compliance" stackId="1" stroke="#f59e0b" fill="#f59e0b" fillOpacity={0.6} />
                    <Area type="monotone" dataKey="operational" stackId="1" stroke="#3b82f6" fill="#3b82f6" fillOpacity={0.6} />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
              <div className="h-80 bg-[#0f1623] rounded-xl border border-[#2a3548] p-6">
                <h3 className="text-white font-semibold mb-4">Audit Status Distribution</h3>
                <ResponsiveContainer width="100%" height="85%">
                  <BarChart data={auditStatusData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2a3548" />
                    <XAxis dataKey="status" tick={{ fill: '#94a3b8', fontSize: 10 }} />
                    <YAxis tick={{ fill: '#94a3b8' }} />
                    <Tooltip content={<CustomTooltip />} />
                    <Bar dataKey="count" fill="#8b5cf6" radius={[8, 8, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Framework Performance Grid */}
      <Card className="bg-[#1a2332] border-[#2a3548]">
        <CardHeader>
          <CardTitle className="text-white flex items-center gap-2">
            <Activity className="h-5 w-5 text-emerald-400" />
            Framework Compliance Overview
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
            {frameworkComplianceData.map((framework, idx) => (
              <div key={idx} className="p-4 rounded-xl bg-[#0f1623] border border-[#2a3548] hover:border-[#3a4558] transition-all">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="text-white font-semibold text-sm">{framework.framework}</h4>
                  <Badge className={`${
                    framework.compliance >= 80 ? 'bg-emerald-500/20 text-emerald-400' :
                    framework.compliance >= 60 ? 'bg-amber-500/20 text-amber-400' :
                    'bg-rose-500/20 text-rose-400'
                  }`}>
                    {framework.compliance}%
                  </Badge>
                </div>
                <Progress value={framework.compliance} className="h-2.5 mb-3" />
                <div className="flex items-center justify-between text-xs text-slate-400">
                  <span>{framework.compliant}/{framework.total}</span>
                  <span className="text-emerald-400 font-medium">Compliant</span>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Critical Issues Requiring Action */}
      {criticalIssues.length > 0 && (
        <Card className="bg-gradient-to-br from-[#1a2332] to-[#151d2e] border-rose-500/30 shadow-xl">
          <CardHeader className="border-b border-[#2a3548]">
            <div className="flex items-center justify-between">
              <CardTitle className="text-white flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-rose-400" />
                Critical Issues - Action Required
              </CardTitle>
              <Badge className="bg-rose-500/20 text-rose-400">
                {criticalIssues.length} Items
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="space-y-3">
              {criticalIssues.map((issue, idx) => (
                <div key={idx} className="p-4 rounded-lg bg-[#0f1623] border border-[#2a3548] hover:border-rose-500/40 transition-all">
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <Badge className={`${
                          issue.type === 'risk' ? 'bg-rose-500/20 text-rose-400' : 'bg-amber-500/20 text-amber-400'
                        }`}>
                          {issue.type === 'risk' ? 'Risk' : 'Compliance Gap'}
                        </Badge>
                        <span className="text-white font-medium text-sm">{issue.title || issue.name || issue.requirement}</span>
                      </div>
                      <p className="text-xs text-slate-400 line-clamp-2">{issue.description}</p>
                    </div>
                    <Button 
                      size="sm" 
                      onClick={() => openQuickAction(issue, issue.type)}
                      className="bg-indigo-600 hover:bg-indigo-700 ml-4"
                    >
                      Create Task
                    </Button>
                  </div>
                  <div className="flex items-center gap-4 text-xs text-slate-500 mt-2">
                    {issue.type === 'risk' && (
                      <>
                        <span>Severity: <span className="text-rose-400 font-medium">{issue.risk_level || 'High'}</span></span>
                        <span>Impact: <span className="text-slate-300">{issue.impact || 'N/A'}/5</span></span>
                      </>
                    )}
                    {issue.type === 'compliance' && (
                      <>
                        <span>Framework: <span className="text-amber-400 font-medium">{issue.framework}</span></span>
                        <span>Status: <span className="text-slate-300">{issue.status}</span></span>
                      </>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Quick Reports */}
      <Card className="bg-[#1a2332] border-[#2a3548]">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Zap className="h-5 w-5 text-amber-400" />
            Quick Report Generation
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {quickReports.map((report, idx) => {
              const Icon = report.icon;
              return (
                <Card key={idx} className="bg-[#151d2e] border-[#2a3548] hover:border-indigo-500/40 transition-all cursor-pointer group">
                  <CardContent className="p-5">
                    <div className={`p-3 rounded-xl bg-gradient-to-br ${report.color}/20 w-fit mb-3 group-hover:scale-110 transition-transform`}>
                      <Icon className="h-6 w-6 text-white" />
                    </div>
                    <h3 className="text-base font-semibold text-white mb-1">{report.title}</h3>
                    <p className="text-sm text-slate-400 mb-4">{report.description}</p>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" className="flex-1 border-[#2a3548]">
                        <FileBarChart className="h-3 w-3 mr-2" />
                        Generate
                      </Button>
                      <Button variant="ghost" size="sm" className="bg-gradient-to-r from-purple-600/20 to-pink-600/20 hover:from-purple-600/30 hover:to-pink-600/30 border border-purple-500/30">
                        <Download className="h-3 w-3" />
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </CardContent>
      </Card>

      <QuickActionPanel 
        open={quickActionOpen}
        onOpenChange={setQuickActionOpen}
        issue={selectedIssue}
        issueType={selectedIssueType}
      />
    </div>
  );
}